# Generated by Django 2.2 on 2019-12-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_file_type', models.CharField(choices=[('jpg', 'jpg-picture'), ('mp4', 'mp4-video')], max_length=10)),
            ],
        ),
    ]
