# Generated by Django 2.2 on 2020-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='uploadedFile',
        ),
    ]
