# Generated by Django 2.2 on 2020-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0002_auto_20200104_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifile_name', models.CharField(max_length=100)),
                ('ofile_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('ifile', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
