# Generated by Django 2.2 on 2020-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0003_auto_20200105_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='d_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='ifile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='ofile_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
