# Generated by Django 2.2 on 2020-01-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0004_auto_20200105_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='task_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
