# Generated by Django 2.2 on 2020-01-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0005_auto_20200105_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='ofile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
